[package]
authors = []
name = "hello_world"
version = "0.0.1"

[[bin]]
name = "hello_world"
path = "main.rs"

[dependencies]
piston = "0.20.0"
tcod = "0.9.0"

[dependencies.tcod_window]
path = "../../"
